### ISSUE TITLE
Memory leak trying to deserialize a complex object when it comes a null value in a child object

### ISSUE THREAD

**Issue by Himhotep** [paolo-rossi/delphi-neon#21]
You can test it with the NeonMainDemo project:
- Go to 'Complex Types' tab.
- Set {"name": "Paolo", "Note": null} in the Serialize memo.
- Press Complex Object at Deserialize.
- Close the application.

* How can this be avoided?
* Is there a way to not have to create the properties in the constructor of the parent object?
TPerson.Create constructor;
begin
  FNote: = TNote.Create;
...

Thanks and great job!

**Comment by alanhci** [comment]
i'm also having memory leak problems, here's the event file generated by FastMM4.

[HCI5BackendApp_MemoryManager_EventLog.txt](https://github.com/paolo-rossi/delphi-neon/files/5143765/HCI5BackendApp_MemoryManager_EventLog.txt)

Im aware that there are some leaks on my application, but there's a lot of leaks in the Core.Persistence.Json.TNeonSerializerJSON.WriteObject too.

**Comment by alanhci** [comment]
Here another log, in this log i've solved all of my application leaks, all leaks are now from the Neon.

[HCI5BackendApp_MemoryManager_EventLog.txt](https://github.com/paolo-rossi/delphi-neon/files/5143840/HCI5BackendApp_MemoryManager_EventLog.txt)

Let me know if you need help with those leaks.

**Comment by paolo-rossi** [comment]
Hi @Himhotep , 

sorry for the (long) response time...

Well, about the "problem" you are having, I want to talk for a moment about the general theory behind a Serializer/Deserializer:

The general rule here is that the Ser/Des must interfere with (sub)object creation and destruction as little as possible, so for example all the objects that the serializer must create they must have a constructor with no parameters because it cannot possibly know the parameters values.. 
The same is for object destruction, and here the rule is more draconian: don't destroy objects, it's not the deserializer job.

Besides, what are you trying to achieve with the semantic of a null object? Are you trying to say that there is no data? Because probably the proper semantic for that would be an empty object {}. Of course you have to have control over the JSON creation to do that.

So, in the end, it's possible to introduce some "configuration" in order to instruct Neon to do a predefined action when it encounters a null value (intended for an object value) but I think we are in thin ice here, if that in not controlled (understood) properly it will end up in a mess for the (sub)objects.

Paolo.

**Comment by paolo-rossi** [comment]
Hi @alanhci ,

can you give me some more information? perhaps provide a reliable test case? I cannot replicate your memory leak. 

Also it's best to probably open another issue, because the problem you are having has nothing to do with what @Himhotep is describing. Thanks.

Paolo.

**Comment by paolo-rossi** [comment]
I'm going to close this issue due to insufficient information to replicate the problem. 

Please feel free to open another issue in you find more on the subject.

Paolo.
