### ISSUE TITLE
error generating swagger json

### ISSUE THREAD

**Issue by defcore** [paolo-rossi/delphi-neon#46]
I have a problem converting this structure into swagger.json. 
If I am calling the /swagger endpoint from WiRL the service crashes. 
If I call the GET endpoint that returns this structure then it works fine.

```
TObjectA = class;

TObjectA = class 
private 
   FNodes: TObjectDictionary<string, TObjectA>
public
   property Nodes : TObjectDictionary<string, TObjectA> read FNodes write FNodes;
end;
```

How can I fix this problem?

Thanks

**Comment by paolo-rossi** [comment]
Hi @defcore ,

at this moment the schema generation doesn't support recursive structures like the one you are describing. 

In theory it's possible using the `schemas ` container in OpenAPI and the `$defs` in JSON schemas to reference already parsed structures but the problem is that they aren't compatible if mixed together.. probably with OpenAPI 3.1 support I can think of something.. but not for now, sorry.

Ciao,
Paolo.
