### ISSUE TITLE
Wrong interpretation of [NeonInclude(IncludeIf.NotEmpty)] ?

### ISSUE THREAD

**Issue by AndyFux** [paolo-rossi/delphi-neon#57]
Hi,
i'm not sure, but from my perpective there is a bug in serialization of properities:

  [NeonInclude(IncludeIf.NotEmpty)]
    property description: string read Getdescription;

"description" will not be serialized when Getdescription() returns a value ...
I'd expect the serialization of "description"  in this case ..
Greetings Andy

**Comment by paolo-rossi** [comment]
Hello Andy,

thank you for taking the time to discuss that... 

Here `description` doesn't get serialized because it's a read-only property, it has nothing to do with the attribute `[NeonInclude(IncludeIf.NotEmpty)]`. You can try adding a write accessor to `description` and see what happens.

Ciao,
Paolo.
