### ISSUE TITLE
Nullable member of Record

### ISSUE THREAD

**Issue by AlexeyM123** [paolo-rossi/delphi-neon#88]
Hello.
How to serialize and deserialize such a record?

```
TMyRecord = record
public
   Speed: TEnumSpeed;
   ...
   Three: Nullable<integer>;
end
```

**Comment by paolo-rossi** [comment]
Hello @AlexeyM123 ,

to serialize this type you can use this code:
```delphi
  var rec: TMyRecord;
  var res := TNeon.ValueToJSONString(TValue.From<TMyRecord>(rec), config);
```

and to deserialize the JSON string into a variable `rec`:
```delphi
  var rec := TNeon.JSONToValue<TMyRecord>(GetJson, config);
```
I hope that this helps you, I'm closing the issue but feel free to ask  again.

Paolo.

**Comment by AlexeyM123** [comment]
Dear Paolo.
Thank you for your lib and your assistance.
I will try to test the solution.

**Comment by AlexeyM123** [comment]
Dear Paolo
I tried TNeon.ValueToJSONString(TValue.From<TMyRecord>(rec))
A value of the nullable record member is omitted in JSON.

**Comment by paolo-rossi** [comment]
Alexey,

strange, I'm testing right now and the value of the field "Three" gets serialized (if it's not null)

I attach my test project (please rename it in TestIssue_88.dpr)
[TestIssue_88.txt](https://github.com/paolo-rossi/delphi-neon/files/14757372/TestIssue_88.txt)

Paolo.

**Comment by AlexeyM123** [comment]
Dear Paolo
Maybe I misunderstand the issue.
I expect 
[{
    "Three": null
}](url)

**Comment by paolo-rossi** [comment]
Hello Alexey,

Ok now I see...

I will give you the explanation and a simple workaround, but I'm thinking to change that in a next release:

[Explanation]
The problem lies in the definition of the IncludeIf enum (Neon.Core.Attributes.pas line 92), as you can see the first enum (the default) is `NotNull` so all the properties/fields have a default of `NotNull` when serializing/deserializing meaning that **Neon** will skip that property/field if `nil`.

Now, it's probably better to have Always as default for props/fields but this will be a breaking change although I'm surely evaluating the change..

[Workaround]
Please annotate the `Three` property with IncludeIf.Always like that:

```delphi
[NeonInclude(IncludeIf.Always)]
Three: Nullable<integer>;
```

If and when I change the default then you can remove the attribute (but in your case it doesn't change the result)

Ciao,
Paolo.

**Comment by AlexeyM123** [comment]
Dear Paolo
Thank you. Very appreciated
